
<<<<<<< HEAD

server:
  port: 8080
  mode: production

server:
  port: 3000
  mode: development

# Experimental Application Configuration
application:
  name: DevOpsSimulator
  version: 3.0.0-experimental
  environment: testing
  experimental_mode: true
  
server:
  host: 0.0.0.0
  port: 9000
  ssl_enabled: true
  multi_port: [9000, 9001, 9002]
  
logging:
  level: TRACE
  format: structured
  output: /var/log/experimental.log
  ai_analysis: enabled
  
database:
  host: cluster.example.com
  port: 5432
  name: devops_experimental
  distributed: true
  
features:
  auto_scaling: advanced
  load_balancer: ai-optimized
  backup_enabled: true
  chaos_engineering: enabled
  
ai_features:
  predictive_scaling: true
  anomaly_detection: true
  auto_optimization: true
  model_version: "v2.1.0"
  
cloud_providers:
  - aws
  - azure
  - gcp
  - digitalocean
  
security:
  zero_trust: enabled
  encryption: AES-256
  audit_logging: comprehensive
conflict-simulator
=======
server:
  port: 8080
  mode: production
=======
server:
  port: 3000
  mode: development
>>>>>>> 1f14a53590bf1d28ff75c386288d495cc20eea2b
