
application:
  name: DevOpsSimulator
  version: 1.0.0
  environment: production
  
server:
  host: 0.0.0.0
  port: 8080
  ssl_enabled: true
  
development:
  host: localhost
  port: 3000
  ssl_enabled: false
  
